### PR TITLE
fix: throw an error for non observable arg

### LINKED ISSUE #2: Conversion of non-promises to promises is problematic for AVA
#1 Causes every argument to be converted to a via `Promise.resolve()`. That creates a small problem for AVA, since [this line](https://github.com/sindresorhus/ava/blob/dcf84b6f867d7b7aece83e59dcf99cbbc05a7bdc/lib/assert.js#L72) expects `isPromise(fn)` to be false if a `function` was passed in.

Also, the current behavior creates ambiguity, as:

``` js
observableToPromise([1,2]);
```

Produces an identical result to:

``` js
observableToPromise(Observable.of(1,2));
```

### PR DESCRIPTION
**Pull request by mastilver**
closes: #2

### CODE REVIEW

**Comment by jamestalmage** [comment]
update the readme.

Otherwise :+1:

**Comment by mastilver** [comment]
I'm just removing: `Other values are just passed through.`, right?

**Comment by jamestalmage** [comment]
Works for me. @sindresorhus?

**Comment by sindresorhus** [comment]
:+1:

**Pull request merged**
